# Generated by Django 4.2.28 on 2026-02-09 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('standard', 'Standard User'), ('manager', 'Manager'), ('admin', 'Authority Admin')], default='standard', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to='authorities.authority')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
