# Generated by Django 5.2.11 on 2026-02-11 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0003_agency_routingrule'),
        ('authority_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorityprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='authorityprofile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='authorities.agency'),
        ),
    ]
