# Generated by Django 5.2.11 on 2026-02-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0004_remove_authority_users_and_more'),
        ('authority_users', '0002_remove_authorityprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorityprofile',
            name='authority',
        ),
        migrations.AlterField(
            model_name='authorityprofile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to='authorities.agency'),
        ),
    ]
