# Generated by Django 4.2.28 on 2026-02-09 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=50.0)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('verified_reports', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('reporter_factor', models.FloatField(default=0.0)),
                ('confirmation_factor', models.FloatField(default=0.0)),
                ('media_factor', models.FloatField(default=0.0)),
                ('spatial_factor', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to='reports.report')),
            ],
        ),
    ]
