# Generated by Django 4.2.28 on 2026-02-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('digital_signature', models.TextField(blank=True, help_text='Digital acknowledgement record/audit trail')),
                ('is_official', models.BooleanField(default=True)),
            ],
        ),
    ]
