# Generated by Django 4.2.28 on 2026-02-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority_level', models.CharField(max_length=20, unique=True)),
                ('resolution_time_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SLATracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('due_time', models.DateTimeField()),
                ('is_breached', models.BooleanField(default=False)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='cases.case')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sla.slapolicy')),
            ],
        ),
    ]
