# Generated by Django 4.2.28 on 2026-02-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(help_text='Format: lat,lng', max_length=255),
        ),
    ]
