# Generated by Django 4.2.28 on 2026-02-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', models.TextField(help_text='GeoJSON boundary data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
