# Generated by Django 4.2.28 on 2026-02-09 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorities', '0001_initial'),
        ('geo', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityassignment',
            name='infra_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.infrastructuretype'),
        ),
        migrations.AddField(
            model_name='authorityassignment',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.jurisdiction'),
        ),
        migrations.AddField(
            model_name='authority',
            name='users',
            field=models.ManyToManyField(related_name='authorities', to=settings.AUTH_USER_MODEL),
        ),
    ]
