# Generated by Django 5.2.11 on 2026-02-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0003_agency_routingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='users',
        ),
        migrations.RemoveField(
            model_name='authorityassignment',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='authorityassignment',
            name='infra_type',
        ),
        migrations.RemoveField(
            model_name='authorityassignment',
            name='jurisdiction',
        ),
    ]
