# Generated by Django 5.2.11 on 2026-02-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0004_remove_authority_users_and_more'),
        ('authority_users', '0003_remove_authorityprofile_authority_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='AuthorityAssignment',
        ),
    ]
